"""Standalone read-only viewer for the research ledger.

Binds 127.0.0.1 only. There is no POST route and nothing here can act.

Data source, in order of preference:
  1. answers.json            - the live ledger, regenerated by the graders
  2. ui/snapshot/answers.json - the committed snapshot shipped with the repo

The fallback is the point: a fresh clone on any machine reads the same registered
questions and verdicts without needing the sibling repos the graders run against.
The page states which source it is showing and as of when.

Staleness is recomputed from `as_of` against the clock rather than read from the
`stale` field, which records what was true when the file was written.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from flask import Flask, jsonify, render_template

REPO_ROOT = Path(__file__).resolve().parent.parent
LIVE = REPO_ROOT / "answers.json"
SNAPSHOT = Path(__file__).resolve().parent / "snapshot" / "answers.json"

# A ledger is allowed to be older than a daily flag; it only moves when a grader
# is re-run. Two weeks matches the staleness window the console used.
STALE_DAYS = 14

# Verdict grouping. The point of the ledger is that a NO is a first-class answer
# and an unanswered question is not quietly dropped, so the ordering puts
# settled verdicts first and open work last rather than ranking by sentiment.
SETTLED = {"NO", "ANSWERED", "RESOLVED", "FIXED", "CONCERN-NOT-SUPPORTED",
           "REAL-BUT-NOT-SIGNIFICANT", "NO-SUPERSEDED"}
PROVISIONAL = {"NEWS-PROVISIONAL", "NO-DATA"}
OPEN = {"OPEN", "OPEN-POLICY"}

app = Flask(__name__)


# Browsers reject NaN/Infinity in JSON, which left the page stuck on "loading...".
# Emit them as null so the tables render; missing stats already show as "–".
import math as _math
from flask.json.provider import DefaultJSONProvider as _DJP


def _finite(o):
    if isinstance(o, float) and not _math.isfinite(o):
        return None
    if isinstance(o, dict):
        return {k: _finite(v) for k, v in o.items()}
    if isinstance(o, (list, tuple)):
        return [_finite(v) for v in o]
    return o


class _FiniteJSON(_DJP):
    def dumps(self, obj, **kw):
        return super().dumps(_finite(obj), **kw)


app.json = _FiniteJSON(app)


def _parse_ts(value) -> datetime | None:
    try:
        ts = datetime.fromisoformat(str(value))
    except Exception:
        return None
    return ts if ts.tzinfo else ts.replace(tzinfo=timezone.utc)


def _bucket(status: str) -> str:
    if status in SETTLED:
        return "settled"
    if status in PROVISIONAL:
        return "provisional"
    if status in OPEN:
        return "open"
    return "other"


def _load() -> dict:
    """Live ledger if present and parseable, else the shipped snapshot."""
    for path, source in ((LIVE, "live"), (SNAPSHOT, "snapshot")):
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except Exception:
            continue
        if isinstance(data, dict):
            data["_source"] = source
            data["_source_path"] = str(path.relative_to(REPO_ROOT))
            return data
    return {
        "_source": "none",
        "_source_path": "",
        "stale": True,
        "answers": [],
        "counts": {},
        "note": "no ledger and no snapshot found",
    }


def _age(state: dict) -> None:
    ts = _parse_ts(state.get("as_of"))
    if ts is None:
        state["stale"] = True
        state["age_days"] = None
        return
    age = (datetime.now(timezone.utc) - ts).total_seconds() / 86400.0
    state["age_days"] = round(age, 1)
    state["stale"] = age > STALE_DAYS


_BUCKET_ORDER = {"settled": 0, "provisional": 1, "open": 2, "other": 3}


def _rows(state: dict) -> list[dict]:
    rows = []
    for a in state.get("answers") or []:
        if not isinstance(a, dict):
            continue
        status = str(a.get("status") or "?")
        rows.append({
            "id": a.get("id"),
            "question": a.get("question"),
            "repo": a.get("repo"),
            "status": status,
            "bucket": _bucket(status),
            "registration": a.get("registration"),
            "yes_bar": a.get("yes_bar"),
            "result": a.get("result") or "",
            "result_as_of": a.get("result_as_of"),
            "note": a.get("note") or "",
            "answered_by": a.get("answered_by"),
            "evidence_as_of": a.get("evidence_as_of"),
        })
    rows.sort(key=lambda r: (_BUCKET_ORDER.get(r["bucket"], 9), str(r["id"])))
    return rows


@app.route("/")
def page_index():
    return render_template("index.html")


@app.route("/api/answers")
def api_answers():
    state = _load()
    _age(state)
    rows = _rows(state)
    state["rows"] = rows
    state["n_questions"] = len(rows)
    state["n_prereg"] = sum(1 for r in rows if r["registration"] == "pre-registered")
    state["n_open"] = sum(1 for r in rows if r["bucket"] == "open")
    state["n_no"] = sum(1 for r in rows if r["status"] == "NO")
    # Drop the bulky nested blocks the page does not render.
    for k in ("flags", "scorecard_freshness", "meta"):
        state.pop(k, None)
    return jsonify(state)


@app.route("/health")
def health():
    return jsonify({"ok": True, "ts": datetime.now(timezone.utc).isoformat()})


def main() -> None:
    # 127.0.0.1 only. Never 0.0.0.0, never tunnelled.
    app.run(host="127.0.0.1", port=8104, debug=False)


if __name__ == "__main__":
    main()
